[package]
name = "klask"
version = "0.1.0"
authors = ["Michal Gniadek <mgniadek@interia.pl>"]
edition = "2018"

[dependencies]
Inflector = "0.11.4"
cansi = "2.1.1"
clap = "3.0.0-beta.4"
eframe = "0.14.0"
linkify = "0.7"
native-dialog = "0.5.5"
uuid = { version = "0.8.2", features = ["v4"] }
