[package]
name = "klask"
version = "0.2.1"
authors = ["Michał Gniadek <mgniadek@interia.pl>"]
edition = "2018"
license = "MIT"
description = "Automatically create GUI for clap apps"
repository = "https://github.com/MichalGniadek/klask"

[dependencies]
Inflector = "0.11.4"
cansi = "2.1.1"
clap = "3.0.0-beta.4"
eframe = "0.14.0"
linkify = "0.7"
native-dialog = "0.5.5"
thiserror = "1.0.29"
uuid = { version = "0.8.2", features = ["v4"] }
