[package]
name = "klask"
version = "0.3.1"
authors = ["Michał Gniadek <mgniadek@interia.pl>"]
edition = "2018"
license = "MIT"
description = "Automatically create GUI for clap apps"
repository = "https://github.com/MichalGniadek/klask"
categories = ["gui"]
keywords = ["clap", "gui", "ui", "cli", "egui"]

# When you change clap's beta version you have to change it
# in clap and clap_derive.
[dependencies]
Inflector = { version = "0.11.4", default-features = false }
clap = { version = "=3.0.0-beta.4", default-features = false, features = [
    "std",
    "derive",
] }
clap_derive = "=3.0.0-beta.4"
uuid = { version = "0.8.2", features = ["v4"] }
cansi = "2.1.1"
eframe = "0.14.0"
linkify = "0.7"
thiserror = "1.0.29"

[target.'cfg(not(target_os = "windows"))'.dependencies]
native-dialog = "0.5.5"

# Should make dialogs look better
[target.'cfg(target_os = "windows")'.dependencies]
native-dialog = { version = "0.5.5", features = [
    "windows_dpi_awareness",
    "windows_visual_styles",
] }
